export const data = [
  {
    id: 1,
    img: "https://media-assets.swiggy.com/swiggy/image/upload/f_auto,q_auto,fl_lossy/f596863116da4b4688b48e813e25000d",
    name: "Burgur",
    des: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    category: "FastFood",
    starting: "100",
  },
  {
    id: 2,
    img: "https://www.allrecipes.com/thmb/iXKYAl17eIEnvhLtb4WxM7wKqTc=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/240376-homemade-pepperoni-pizza-Beauty-3x4-1-6ae54059c23348b3b9a703b6a3067a44.jpg",
    name: "Pizaa",
    des: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    category: "FastFood",
    starting: "299",
  },
  {
    id: 3,
    img: "https://static.toiimg.com/thumb/61048461.cms?imgsize=1981854&width=800&height=800",
    name: "Panipuri",
    des: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    category: "FastFood",
    starting: "49",
  },
  {
    id: 4,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRvYGJsnFbaWQn0VvZwmILuF1Vre-R5HbETkQ&s",
    name: "Khichadi",
    des: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    category: "Dinner",
    starting: "89",
  },
  {
    id: 5,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcST4zutLMn9Xz8PssiedyitmqLp2N99GvOzp2nkc6ZBtg&s",
    name: "Dhosa",
    des: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    category: "Dinner",
    starting: "129",
  },
  {
    id: 6,
    img: "https://i.pinimg.com/originals/ec/fd/51/ecfd515c17f275addd63cdfa16a11ca1.jpg",
    name: "DalBhat",
    des: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    category: "Lunch",
    starting: "149",
  },
  {
    id: 7,
    img: "https://www.cookwithmanali.com/wp-content/uploads/2018/04/Vada-Pav-500x375.jpg",
    name: "vadapav",
    des: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    category: "FastFood",
    starting: "39",
  },
  {
    id: 8,
    img: "https://content.jdmagicbox.com/comp/noida/v8/011pxx11.xx11.190925042619.e8v8/catalogue/punjabi-chole-bhature-noida-sector-34-noida-north-indian-restaurants-2whbntunqe.jpg",
    name: "Cholebhature",
    des: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    category: "Lunch",
    starting: "69",
  },
  {
    id: 9,
    img: "https://www.nehascookbook.com/wp-content/uploads/2021/08/Instant-handvo-WS.jpg",
    name: "Handvo",
    des: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    category: "Dinner",
    starting: "119",
  },
  {
    id: 10,
    img: "https://www.archanaskitchen.com/images/archanaskitchen/Indian_Sweets_Mithai/Gujarati_Lapsi_Broken_Wheat_Pudding_Recipe-1.jpg",
    name: "Lapsi",
    des: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    category: "Lunch",
    starting: "99",
  },
  {
    id: 11,
    img: "https://bachelorrecipe.com/wp-content/uploads/2018/05/Vegetable-Sandwich.jpg",
    name: "sandwich",
    des: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    category: "FastFood",
    starting: "139",
  },
  {
    id: 12,
    img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcREPXuVX-gdqxYHEpE23W9tqSTKuSqdqm22blGa4CJtjA&s",
    name: "Locho",
    des: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.",
    category: "FastFood",
    starting: "79",
  },
];

export const categories = [
    {
        categoryname : "FastFood",
    },
    {
        categoryname : "Lunch",
    },
    {
        categoryname : "Dinner",
    },
]
